title: "No Budget Sec"
name: "Nahuel Perez"
description: "Blog about information security and technology"
url: "https://nobudgetsec.github.io"
baseurl: ""  # importante para github.io root
remote_theme: "mmistakes/minimal-mistakes@4.27.1"

# Logo for the site masthead
logo: "/assets/images/logo.svg"

# Include _pages directory
include:
  - _pages

# Site Settings
locale: "en-US"
search: true
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Author
author:
  name: "Nahuel Perez"
  bio: "Cybersecurity Enthusiast"
  location: "Canada"
  avatar: "/assets/images/profile.png"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jnahuelperez/"

# Site Footer
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jnahuelperez/"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      header:
        show: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      header: 
        show: false

paginate: 5
paginate_path: /page:num/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate
  - jekyll-include-cache
