title: "No Budget Security"
name: "Nahuel Perez"
description: "Blog sobre seguridad informática y tecnología"
url: "https://nobudgetsec.github.io"
baseurl: ""  # importante para github.io root
remote_theme: "mmistakes/minimal-mistakes@4.27.1"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate
  - jekyll-paginate-v2
  - jekyll-include-cache
