title: "Mi Blog"
name: "Juan Pérez"
description: "Blog sobre tecnología y seguridad"
url: "https://<tu-usuario>.github.io"
baseurl: ""  # importante para github.io root
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate
  - jekyll-paginate-v2
  - jekyll-include-cache
